/* Builds src/lib/questions/icons.ts and src/lib/plans/icons.ts from the clay set in clay.mjs.
   Run from webapp/:  node tools/icons/build.mjs
   Add or change an icon in clay.mjs, run this, commit both. See DESIGN.md → Icons. */
import { writeFileSync } from 'node:fs';
import { ICONS } from './clay.mjs';

const PLAN = ['pdf', 'image', 'dwg', 'camera', 'upload', 'pencil'];
const q = (s) => JSON.stringify(s);
const withAria = (svg) => svg.replace('<svg ', '<svg aria-hidden="true" ');

const questions = Object.entries(ICONS).filter(([k]) => !PLAN.includes(k));
const plans = Object.entries(ICONS).filter(([k]) => PLAN.includes(k));

writeFileSync(
	'src/lib/questions/icons.ts',
	`/* GENERATED by tools/icons/build.mjs from tools/icons/clay.mjs — do not edit by hand. */
export const ICONS: Record<string, string> = {
${questions.map(([k, v]) => `\t${k}: ${q(withAria(v))}`).join(',\n')}
};

/** The clay icon for \`name\`, or '' when there is none. Sized by its container (\`.ico\`). */
export function ico(name: string): string {
	return ICONS[name] ?? '';
}

export const TICK =
	'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 13l4 4 10-10"/></svg>';

export const ARROW =
	'<svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 10h11M10.5 5l5 5-5 5"/></svg>';
`
);

writeFileSync(
	'src/lib/plans/icons.ts',
	`/* GENERATED by tools/icons/build.mjs from tools/icons/clay.mjs — do not edit by hand. */
export const PLAN_ICONS: Record<string, string> = {
${plans.map(([k, v]) => `\t${k}: ${q(withAria(v))}`).join(',\n')}
};

export function pico(name: string): string {
	return PLAN_ICONS[name] ?? '';
}

/** Which icon stands in for a file we cannot thumbnail. */
export function iconForFile(name: string, type: string): string {
	const n = name.toLowerCase();
	if (type === 'application/pdf' || n.endsWith('.pdf')) return 'pdf';
	if (n.endsWith('.dwg') || n.endsWith('.dxf')) return 'dwg';
	return 'image';
}
`
);
console.log(`wrote ${questions.length} question icons and ${plans.length} plan icons`);
